# Generated by Django 2.1.2 on 2018-11-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invernaderos', '0002_auto_20181101_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invernadero',
            name='ubicacion',
            field=models.CharField(blank=True, error_messages={'empty': 'Este campo no debe quedar vacío'}, help_text='Ingrese la ubicación del invernadero', max_length=22, null=True, verbose_name='Ubicacion del invernadero'),
        ),
    ]
