# Generated by Django 2.1.2 on 2018-10-30 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invernaderos', '0003_invernadero_id_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.AlterField(
            model_name='actuador',
            name='id_actuador',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del Actuador'),
        ),
        migrations.AlterField(
            model_name='actuador',
            name='id_dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invernaderos.Dispositivo', verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='actuador',
            name='is_activo',
            field=models.BooleanField(default=False, verbose_name='¿Está activo?'),
        ),
        migrations.AlterField(
            model_name='actuador',
            name='nombre_actuador',
            field=models.CharField(max_length=45, verbose_name='Nombre del Actuador'),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='id_cultivo',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del cultivo'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='estado_dispositivo',
            field=models.CharField(max_length=45, verbose_name='Estado del dispositivo'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='id_dispositivo',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del dispositivo'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='id_invernadero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invernaderos.Invernadero', verbose_name='Invernadero'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='nombre_dispositivo',
            field=models.CharField(max_length=45, verbose_name='Nombre del dispositivo'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='descripcion_etapa',
            field=models.CharField(max_length=150, verbose_name='Descripcion de la etapa'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='id_cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invernaderos.Cultivo', verbose_name='Cultivo'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='id_etapa',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de la etapa'),
        ),
        migrations.AlterField(
            model_name='invernadero',
            name='id_cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invernaderos.Cultivo', verbose_name='Cultivo'),
        ),
        migrations.AlterField(
            model_name='invernadero',
            name='id_invernadero',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del invernadero'),
        ),
        migrations.AlterField(
            model_name='invernadero',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invernaderos.Usuario', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='invernadero',
            name='nombre_invernadero',
            field=models.CharField(max_length=45, verbose_name='Nombre del invernadero'),
        ),
        migrations.AlterField(
            model_name='invernadero',
            name='ubicacion',
            field=models.CharField(max_length=15, verbose_name='Ubicacion del invernadero'),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='id_actuador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='invernaderos.Actuador', verbose_name='Actuador'),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='id_cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invernaderos.Cultivo', verbose_name='Cultivo'),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='id_medicion',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de la medición'),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='id_parametro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invernaderos.Parametro', verbose_name='Parámetro'),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='id_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invernaderos.Sensor', verbose_name='Sensor'),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='magnitud_medicion',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Magnitud de la medición'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='id_cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invernaderos.Cultivo', verbose_name='Cultivo'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='id_parametro',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del parámetro'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='nombre_parametro',
            field=models.CharField(max_length=45, verbose_name='Nombre del parámetro'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='id_dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invernaderos.Dispositivo', verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='id_sensor',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='nombre_sensor',
            field=models.CharField(max_length=45, verbose_name='Nombre del sensor'),
        ),
    ]
