# Generated by Django 2.1.2 on 2018-11-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invernaderos', '0004_remove_parametro_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='id_cultivo',
        ),
        migrations.AddField(
            model_name='actuador',
            name='is_baja',
            field=models.BooleanField(default=False, verbose_name='¿Está de baja?'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='is_baja',
            field=models.BooleanField(default=False, verbose_name='¿Está de baja?'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='is_baja',
            field=models.BooleanField(default=False, verbose_name='¿Está de baja?'),
        ),
        migrations.AddField(
            model_name='invernadero',
            name='is_baja',
            field=models.BooleanField(default=False, verbose_name='¿Está de baja?'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='is_baja',
            field=models.BooleanField(default=False, verbose_name='¿Está de baja?'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='is_baja',
            field=models.BooleanField(default=False, verbose_name='¿Está de baja?'),
        ),
        migrations.DeleteModel(
            name='Etapa',
        ),
    ]
