# Generated by Django 2.1.2 on 2018-11-01 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invernaderos', '0004_auto_20181101_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuador',
            name='id_invernadero',
            field=models.ForeignKey(blank=True, error_messages={'select': 'Debe seleccionar uno de la lista'}, help_text='Invernadero al que se asignará este parámetro', null=True, on_delete=django.db.models.deletion.CASCADE, to='invernaderos.Invernadero', verbose_name='Invernadero'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='id_invernadero',
            field=models.ForeignKey(blank=True, error_messages={'select': 'Debe seleccionar uno de la lista'}, help_text='Invernadero al que se asignará este parámetro', null=True, on_delete=django.db.models.deletion.CASCADE, to='invernaderos.Invernadero', verbose_name='Invernadero'),
        ),
    ]
