# Generated by Django 2.1.2 on 2018-10-31 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invernaderos', '0004_auto_20181030_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='dispositivo',
            options={'ordering': ['id_dispositivo'], 'verbose_name': 'Dispositivo', 'verbose_name_plural': 'Dispositivos'},
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='id_invernadero',
        ),
        migrations.AddField(
            model_name='invernadero',
            name='id_dispositivo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='invernaderos.Dispositivo', verbose_name='Dispositivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invernadero',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
