# Generated by Django 2.1.2 on 2018-11-06 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invernaderos', '0005_auto_20181105_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuador',
            name='id_dispositivo',
            field=models.ForeignKey(blank=True, error_messages={'select': 'Debe seleccionar uno de la lista'}, help_text='Dispositivo que se asociará a este actuador', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invernaderos.Dispositivo', verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='actuador',
            name='id_invernadero',
            field=models.ForeignKey(blank=True, error_messages={'select': 'Debe seleccionar uno de la lista'}, help_text='Invernadero al que se asignará este parámetro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invernaderos.Invernadero', verbose_name='Invernadero'),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='id_usuario',
            field=models.ForeignKey(error_messages={'select': 'Debe seleccionar uno de la lista'}, help_text='Usuario al que pertenece este cultivo', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='invernadero',
            name='id_dispositivo',
            field=models.ForeignKey(blank=True, error_messages={'select': 'Debe seleccionar uno de la lista'}, help_text='Dispositivo que controla este invernadero', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invernaderos.Dispositivo', verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='invernadero',
            name='id_usuario',
            field=models.ForeignKey(blank=True, error_messages={'select': 'Debe seleccionar uno de la lista'}, help_text='Usuario al que pertenece este invernadero', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='id_actuador',
            field=models.ForeignKey(blank=True, error_messages={'select': 'Debe seleccionar uno de la lista'}, help_text='Actuador que responderá a dicha medición', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invernaderos.Actuador', verbose_name='Actuador'),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='id_invernadero',
            field=models.ForeignKey(blank=True, error_messages={'select': 'Debe seleccionar uno de la lista'}, help_text='Invernadero al que se le realizó la medición', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invernaderos.Invernadero', verbose_name='Invernadero'),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='id_parametro',
            field=models.ForeignKey(blank=True, error_messages={'select': 'Debe seleccionar uno de la lista'}, help_text='Parámetro con el que se comparará esta medición', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invernaderos.Parametro', verbose_name='Parámetro'),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='id_sensor',
            field=models.ForeignKey(blank=True, error_messages={'select': 'Debe seleccionar uno de la lista'}, help_text='Sensor con el que se realizó esta medición', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invernaderos.Sensor', verbose_name='Sensor'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='id_invernadero',
            field=models.ForeignKey(blank=True, error_messages={'select': 'Debe seleccionar uno de la lista'}, help_text='Invernadero al que se asignará este parámetro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invernaderos.Invernadero', verbose_name='Invernadero'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='id_dispositivo',
            field=models.ForeignKey(blank=True, error_messages={'select': 'Debe seleccionar uno de la lista'}, help_text='Dispositivo asociado a este sensor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invernaderos.Dispositivo', verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='id_invernadero',
            field=models.ForeignKey(blank=True, error_messages={'select': 'Debe seleccionar uno de la lista'}, help_text='Invernadero al que se asignará este parámetro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invernaderos.Invernadero', verbose_name='Invernadero'),
        ),
    ]
