# Generated by Django 2.1.2 on 2018-11-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invernaderos', '0005_auto_20181101_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invernadero',
            name='id_cultivo',
            field=models.ManyToManyField(error_messages={'select': 'Debe seleccionar uno de la lista'}, help_text='Cultivo que se cosechará en este invernadero', null=True, to='invernaderos.Cultivo', verbose_name='Cultivo'),
        ),
    ]
