# Generated by Django 2.1.2 on 2018-11-01 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invernaderos', '0005_auto_20181030_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invernadero',
            options={'ordering': ['id_invernadero', 'nombre_invernadero'], 'verbose_name': 'Invernadero', 'verbose_name_plural': 'Invernaderos'},
        ),
        migrations.AlterModelOptions(
            name='medicion',
            options={'ordering': ['fecha_medicion', 'id_invernadero', 'id_sensor', 'id_parametro', 'id_actuador'], 'verbose_name': 'Medicion', 'verbose_name_plural': 'Mediciones'},
        ),
        migrations.AlterModelOptions(
            name='parametro',
            options={'ordering': ['id_invernadero', 'nombre_parametro'], 'verbose_name': 'Parámetro', 'verbose_name_plural': 'Parámetros'},
        ),
        migrations.RemoveField(
            model_name='medicion',
            name='id_cultivo',
        ),
        migrations.RemoveField(
            model_name='parametro',
            name='id_cultivo',
        ),
        migrations.AddField(
            model_name='medicion',
            name='id_invernadero',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='invernaderos.Invernadero', verbose_name='Invernadero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametro',
            name='id_invernadero',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='invernaderos.Invernadero', verbose_name='Invernadero'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='id_cultivo',
            field=models.AutoField(error_messages={'exist': 'El indentificador ya existe'}, help_text='Identificador genérico del cultivo', primary_key=True, serialize=False, verbose_name='Codigo del cultivo'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='id_cultivo',
            field=models.ForeignKey(help_text='Cultivo al que pertenece esta etapa', on_delete=django.db.models.deletion.CASCADE, to='invernaderos.Cultivo', verbose_name='Cultivo'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='id_etapa',
            field=models.AutoField(error_messages={'exist': 'El indentificador ya existe'}, help_text='Identificador genérico de la Etapa', primary_key=True, serialize=False, verbose_name='Codigo de la etapa'),
        ),
        migrations.RemoveField(
            model_name='invernadero',
            name='id_cultivo',
        ),
        migrations.AddField(
            model_name='invernadero',
            name='id_cultivo',
            field=models.ManyToManyField(to='invernaderos.Cultivo', verbose_name='Cultivo'),
        ),
    ]
