# Generated by Django 2.1.2 on 2018-11-06 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invernaderos', '0006_auto_20181105_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicion',
            options={'ordering': ['id_invernadero', 'fecha_medicion', 'id_sensor', 'id_parametro', 'id_actuador'], 'verbose_name': 'Medicion', 'verbose_name_plural': 'Mediciones'},
        ),
    ]
